[package]
name = "helo_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
miette = "7.2"
imbl = "2.0"
thiserror = "1.0"
nom = "7.1"
