[package]
name = "helo_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7"
helo_macro = { path = "../helo_macro" }
tabled = "0.14"
